--
-- PKS_LOG
--
  CREATE TABLE "PKS_LOG" 
   (
    "ID" NUMBER(*,0) NOT NULL ENABLE,
    "SYSTEM" NVARCHAR2(20) NOT NULL ENABLE,
    "LOGLEVEL" NVARCHAR2(10) NOT NULL ENABLE,
    "CREATEDDATE" DATE NOT NULL ENABLE,
    "MESSAGE" NVARCHAR2(2000),
    "REQUEST" NVARCHAR2(2000),
    "PRINCIPAL" NVARCHAR2(1000),
    "EXSOURCE" NVARCHAR2(2000),
    "EXCONTENT" NCLOB,
    "EXDATA" NCLOB,
    CONSTRAINT "PK_PKS_LOG" PRIMARY KEY ("ID") ENABLE
   );

--
-- SEQ_PKS_LOG
--
  CREATE SEQUENCE "SEQ_PKS_LOG" MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 CACHE 5 NOORDER NOCYCLE;

--
-- TRIGGER_SYS_LOG
--
  CREATE OR REPLACE TRIGGER "TRIGGER_PKS_LOG"
  BEFORE INSERT ON "PKS_LOG" FOR EACH ROW
  BEGIN
    SELECT SYSFRAME.SEQ_PKS_LOG.NEXTVAL INTO:NEW.ID FROM SYS.DUAL;
  END;

--
-- INX_PK_LOG_LEVEL
--
CREATE INDEX "INX_PK_LOG_LEVEL"  ON "PKS_LOG" ( "LOGLEVEL");
