//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKS.DbModels.Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKS_USERBEHAVIOR
    {
        public int Id { get; set; }
        public string IIID { get; set; }
        public int USERID { get; set; }
        public bool FAVORITEFLAG { get; set; }
        public Nullable<int> FAVORITECATALOGID { get; set; }
        public Nullable<System.DateTime> FAVORITEDATE { get; set; }
        public int DOWNLOADCOUNT { get; set; }
        public Nullable<System.DateTime> DOWNLOADDATE { get; set; }
    
        public virtual PKS_FAVORITECATALOG PKS_FAVORITECATALOG { get; set; }
    }
}
