//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKS.DbModels.Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKS_FAVORITECATALOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PKS_FAVORITECATALOG()
        {
            this.PKS_FAVORITECATALOG1 = new HashSet<PKS_FAVORITECATALOG>();
            this.PKS_USERBEHAVIOR = new HashSet<PKS_USERBEHAVIOR>();
        }
    
        public int Id { get; set; }
        public int USERID { get; set; }
        public string FAVNAME { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUODATEDDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PKS_FAVORITECATALOG> PKS_FAVORITECATALOG1 { get; set; }
        public virtual PKS_FAVORITECATALOG PKS_FAVORITECATALOG2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PKS_USERBEHAVIOR> PKS_USERBEHAVIOR { get; set; }
    }
}
